### ISSUE TITLE
Gulp should start bin/www instead of app.js

### ISSUE THREAD

**Issue by r3dpoint** [koroandr/generator-express-typescript#2] opened 2016-02-25 01:22 UTC
running gulp doesn't result in node starting on port 3000. https://github.com/narirou/gulp-develop-server/issues/4 references the correct fix to start the server at bin/www path.

**Comment by koroandr** [comment] 2016-03-05 07:36
Sorry for long waiting, the issue is now fixed.

**Closed as completed by koroandr** 2016-03-05 07:36 UTC

**Comment by r3dpoint** [comment] 2016-03-05 15:49
verified. thank you!
